---
title: "Bren Organizations & Committees"
---

There are lots of fun ways to get involved at Bren, from joining clubs and committees to sports, health and wellness with peers. Explore all the different opportunities on the [Bren website](https://bren.ucsb.edu/bren-student-activities) and contact academics@bren.ucsb.edu with any questions.

MEDS students serve as class representatives on five different committees. Self-nominations and elections take place in Summer Quarter. The 2022 cohort representatives are listed in the table below. For a complete list of all committees representatives, please visit the [Bren School Committee Directory](https://bren.ucsb.edu/bren-school-committees). 

### MEDS 2022 Cohort Committee Representatives 

| Committee                      | MEDS Representative(s)                       | 
|--------------------------------|----------------------------------------------|
| Class Chairs                   | [Joe DeCesaro](https://bren.ucsb.edu/people/joseph-joe-decesaro) & [Paloma Cartwright](https://bren.ucsb.edu/people/paloma-cartwright) | 
| Master's Curriculum Committee  | [Allie Cole](https://bren.ucsb.edu/people/ingrid-allie-cole) |
| Capstone Project Committee     | [Cullen Molitor](https://bren.ucsb.edu/people/cullen-molitor) & [Alex Yousefivand](https://bren.ucsb.edu/people/alex-yousefivand-vand) |
| NCEAS Roundtable Committee     | [Scout Leonard](https://bren.ucsb.edu/people/scout-leonard) |
| Diversity Committee            | [Halina Do-Linh](https://bren.ucsb.edu/people/halina-do-linh) |
| Dean's Advisory Council (DAC)  | Joe DeCesaro, Paloma Cartwright & Allie Cole |
