---
title: "MEDS Capstone Projects"
---

The MEDS program ends with a group Capstone project where students work in teams of 3-4 to design, develop and share a deliverable that helps a client to gain insights, answer questions, and/or create communication materials using environmental data. The goal of the MEDS Capstone is to help students build real-world data science and professional skills while working with a client to complete a project using environmental data. 

The [Request for Proposals](https://bren.ucsb.edu/research/masters-research/request-proposals-meds) opens in the Spring for the following year. For more information about Capstone projects please visit the Bren School [MEDS Capstone Projects](https://bren.ucsb.edu/masters-programs/master-environmental-data-science/meds-capstone-projects).

## Timeline

### Summer

Bren School releases a MEDS [Request for Proposals](https://bren.ucsb.edu/research/masters-research/request-proposals-meds). Proposals for MEDS Capstone Projects may be submitted by faculty, students, and prospective clients.

### Fall

Submission period for new proposals ends. A committee of students, faculty, and staff selects appropriate projects. Students vote on and join project teams at the end of Fall Quarter.

### Winter

Students meet clients, refine project objectives, develop a design and implementation plan, host a meeting with the client and advisors, and begin preliminary product development.

### Spring

Students complete data science products, write technical documentation, host a meeting with the client and advisors, and present their work in a final product demonstration or visualization.

<!-- |Summer 2022        | Activity                | -->
<!-- |-------------------|-------------------------| -->
<!-- | August 11          | [Capstone project kickoff](https://docs.google.com/presentation/d/1LZCSsSWMCEL2dKqM2RzIjGJWAxC18S6jSpXQGyTDL9Q/edit#slide=id.ge6b7f452cd_0_6982)  | -->
<!-- | August 19         | Writing a capstone project proposal | -->
<!-- | Week 5            | Student nominations for capstone committee  | -->
<!-- | Week 6            | Student elections for capstone committee  | -->
<!-- | **Fall 2022** -->
<!-- | October 14        | Proposals Due           | -->
<!-- | November 16       | Capstone Project Reveal & voting begins | -->
<!-- | Week 10(ish)      | Capstone project assignments announced | -->
<!-- | **Winter 2023** -->
<!-- | February 10       | Draft Design & Implementation plan due   | -->
<!-- | March 8           | Faculty Reviews | -->
<!-- | March 17          | Final Design & Implementation plan due | -->
<!-- | **Spring 2023** -->
<!-- | April 14          | Submit outline of Technical Documentation| -->
<!-- | May 5             | Draft technical documentation & repository due | -->
<!-- | June 2            | Final Presentations | -->
<!-- | June 9            | Final project materials due | -->


## Resources

[Capstone Project Guidelines](https://bren.ucsb.edu/media/5090)  
[Peer & Self Evaluation Form](https://bren.ucsb.edu/media/3922/download)  
[EDS 411A/B Website](https://naomitague.github.io/EDS_411A_meds-capstone/)  
[Compute guide for your google group](https://bren.zendesk.com/hc/en-us/articles/4415068315156-Google-Group-Guide-for-Capstone-Projects)
