---
title: "Career Services & Support"
---

**As a MEDS student, you’ll gain career support to guide your journey to a fulfilling career in environmental data science!** Our Bren MEDS Career Team is here to support you with a career development program including workshops, advising, career guidance emails, job postings, and more. Plus, you’ll also be able to connect with our MEDS program staff, the NCEAS staff, the expansive Bren alumni network, and a variety of professionals working in the field to gain additional industry and career insights.

Below are some highlights of the career support you will get to take advantage of as a MEDS student (for more information, please visit the [Career Services page on the Bren website](https://bren.ucsb.edu/career-services)):

## Career workshops & various speaker events

* **Develop lifelong career development skills through Career Team workshops.** You’ll learn how to navigate your search for your dream job, grow your network, refine your application documents, and gain confidence in interviewing, evaluating offers, and yes, negotiating!
* **Build and customize your own personal professional website in R** with instruction and guidance from MEDS lecturer Allison Horst and Data Training Coordinator Sam Csik.
* **Hear from and connect with various speakers in the environmental and/or data science fields** during [Bren Seminars](https://bren.ucsb.edu/upcoming-events?f%5B0%5D=upcoming-event-category%3A55), [NCEAS Roundtables](https://www.nceas.ucsb.edu/roundtable), class panels, and career talks.

## Example career workshops include: 

* **Introduction to Career Development + BrenConnect**
* **Resume Workshop:** Market Your Resume for the Positions You Want, Not Those You’ve Done
* **Job Search Kickoff Workshop:** Develop Your Job Search Strategy + Action Steps to Begin Now
* **Cover Letter Workshop:** Write + Target Your Cover Letters to Stand Out – The Step-by-Step Bren Approach
* **Interviewing Skills Workshop:** 6 Steps to Rock Every Interview in Your Career – What to Do Before, During, and After
* **Offer Evaluation & Salary Negotiation Workshop:** Why You Shouldn’t Accept or Decline Offers on the Spot, How to Stall, and an Intro to Negotiating

## Bren MEDS career resources & access to alumni
* **Leverage BrenConnect for 24/7 access to 100+ career guidance articles, our Alumni & Student Finder, and our job/internship boards.** BrenConnect is Bren’s student-alumni networking and career resources platform that you’ll use at Bren and beyond. 78.8% of Bren’s 1600+ alumni have joined BrenConnect, and you’ll receive access during the Career Team’s introductory workshop!
* **Receive job, internship, and fellowship alerts via BrenConnect and Slack.** You’ll gain access to 3 platforms to help you search for your dream post-Bren job:
    1.	**The MEDS job/internship opportunities group on BrenConnect** (populated by the Career Team and/or its student assistants, as well as a place for you to share positions with each other)
    2.	 **The Bren-wide job postings group on BrenConnect** (populated by the Career Team, current students, and Bren alumni)
    3.	**The UCSB-MEDS Slack #jobs-fellowships channel** (populated by both MEDS staff and current students)
    
## 1-on-1 career advising & additional industry insights
* **Meet 1-on-1 with our [Bren MEDS Career Team, Dave Parker and Miya Scheble](https://bren.ucsb.edu/career-services), for document reviews, job search check-ins, mock interviews, and other career advising.** As a student, you can reach out to us at medscareer@bren.ucsb.edu for in-person, phone, Zoom, or email advising. We’ll also meet with you for a resume review, and you’ll also have the option to sign up for a job search check-in appointment during the year.
* **Chat with MEDS and NCEAS staff to gain industry insights.** We have lots of exciting career experiences and insights to share. NCEAS is also home to 50+ researchers, data scientists, and educators who are excited to get to know you. You can browse the NCEAS directory [here](https://www.nceas.ucsb.edu/about-us/our-people).
