---
title: "MEDS Slack Workspace"
---

During the MEDS program we will maintain a dedicated [Slack workspace](https://slack.com/) for students, staff and instructors. Staff and instructors will be added by the MEDS coordinator and students will join during the second day of Orientation.

### What is Slack?
It is a communication tool for teams. In its simplest form, it is a platform for live chat. Slack provides users with direct messaging and chat rooms to enable remote collaboration and community exchanges.

### Slack Desktop App
The best way to use Slack is through the Desktop application. At first when you sign up, you may be put into a Slack window in your browser. We recommend downloading the app after joining and setting up your workspace there. This way you can have multiple workspaces open at once. You can find the appropriate download for your operating system [here](https://slack.com/help/categories/360000049043-Getting-started#download-slack).

### Channels

Communication in Slack is done either through direct messages with other Slack members, or through Channels.

Channels are organized by topic and usually have a hashtag (#) in front of them. Our Slack workspace, UCSB-MEDS, contains many channels for conversation. If the instructor agrees, each class will have it's own channel for course-specific discussion. There are also more general channels for announcements, 

You can join any public channel. You can see what channels are public by using the Channel Browser. You can also create your own public channel.

**Private Channels**
  
Anyone in the UCSB-MEDS workspace has the ability to create their own private channels that allow you to determine who can be in that channel. This is really useful for projects that only concern a few team members. We also encourage each cohort to create a single private channel for all students to join.

You can not see private channels that you are not a member of. If you need to join a private channel that you know exists, you can contact the admin team. 

### Direct Messages
A direct message thread is different from a private channel. To open a direct message, go to “Direct Messages” on the left-hand sidebar and click on the plus (+) sign. Then, type in the names of the people who should be part of the direct message thread.

### Notifications
Depending how active a channel is, you might receive a lot of notifications. To lower distractions, Slack lets you customize the level of notifications you want to receive. This can be customized across all channels and direct messages by clicking on the "UCSB-MEDS" in the upper-left and selecting "Preferences". From here you can set up your notifications and decide how often, and by what method, you'd like to be notified. The Do Not Disturb period is very useful in setting up "off-hours" where you won't get any notifications.

### Reactions
Another feature of Slack is the reactions. Anyone can react to a message with an emoji reaction. This is different from sending a message containing that emoji in that it doesn’t trigger notifications. This is hugely helpful. For example, if someone tells you something and you just want to say “OK” or “thanks”, try a reaction instead of a new message, since you don’t really need to notify the person of your response – they will see it next time they are on Slack.

### Edits and deletion
If you want to change something you wrote in Slack, you can always edit the message afterwards. You can also delete messages, for example if you wrote something by accident.

### Message retention
For short term retention of messages, you can click the save icon in the top right corner of a message. Your saved messages will be accessible from the “Saved items” section in the left sidebar (above the “Channels” section). You can also click the three dots in the top right corner of a message to schedule a reminder about that message, so that you remember to read it later.

All UCSB-MEDS Slack messages (including your saved items) will be deleted at the end of each year (at least, all the messages in public channels, which are the ones we can control). If you see something on Slack that you would like to save for after the MEDS program, it is your responsibility to make a copy of it and save it outside Slack.

### Professionalism
We want to maintain a welcoming, inclusive environment both in the classroom and online, including our Slack community. We encourage participation in all private, public and direct messaging channels, however, we ask that you do so respectfully.

Although Slack is a great tool and is constantly available, we expect you to maintain a respectful and professional relationship with your peers, instructors, TA's, and staff. You should not rely on Slack for communication between your instructors and/or TA's unless they have elected to operate their class in that manner.

By joining and using the Bren Slack workspace you are accepting the [University of California Electronic Communications Policy](https://www.policy.ucsb.edu/files/docs/policies/ecp.pdf).

### Privacy
Direct messages can only be read by the people involved. Admin can not view private messages between users or in private channels where they are not a member.

*Parts of this guide were borrowed from the [UBC-MDS Slack Help page](https://ubc-mds.github.io/resources_pages/slack/)*

