---
title: "NCEAS Building Policies"
---

All students are subject to NCEAS’ [Code of Conduct](https://live-ncea-ucsb-edu-v01.pantheonsite.io/sites/default/files/2020-02/NCEAS_Code-of-Conduct_2019.pdf) while at NCEAS.

### Bikes
Do not bring your bike inside the building. All bikes must be kept outside of the building. There are a couple bike parking spots along Anacapa, and a couple in the covered parking garage at our building.

### Kitchen
MEDS students may use the first floor kitchen. This kitchen is also shared with NCEAS. Please be respectful and keep the kitchen clean. This includes washing your dishes, drying and putting them away. Do not leave dishes in the sink. The refrigerator is a shared space that must be kept clean and smell-free. Kitchen privileges can and will be revoked at any time if policies are not followed. 

**Students are only permitted to store food to be consumed that day in the fridge. No alcoholic beverages or long-term storage is allowed.**

Each month we ask a volunteer to do a refrigerator clean out, removing food that has expired and empty forgotten containers. Please sign up to volunteer on the sheet on the fridge.

### After hours access
The NCEAS building is accessible from 7:45 am to 5:00 pm. Currently, students do not have the ability to get into the building outside of these hours and must rely on the presence of an instructor or staff member to let students in. This could change as we settle into the new space and figure out the best ways to manage student access. Your cooperation on this matter is appreciated!

### Whiteboards
Please erase and clean all whiteboards after use and leave markers in their designated spot.

### Pets 
are not allowed. UCSB Campus does not permit dogs in buildings except for service dogs. 

### Third Floor
The building’s third floor is home to many of the NCEAS staff and scientists, as well as our conference rooms and outdoor terrace. The conference rooms are not for student use. If you need private group meeting space, you can reserve the first floor room (#105).

The terrace has an occupancy limit of just 49 people. This unfortunately limits the access we can provide our MEDS students to invited events only.



