---
title: "Program Overview"
output:
  distill::distill_article:
    toc: true
    toc_float: true
    toc_depth: 1
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Here, we share a bit more information about what students can expect during the MEDS program.

# Summer

## Orientation

Each student should plan to attend a 1.5-day MEDS orientation on the Thursday and Friday before the first day of summer classes. Orientation for the MEDS Class of 2022 will be held at Bren Hall (July 29th) and NCEAS (July 30th). During orientation, incoming MEDS students will:

-   Meet the MEDS staff
-   Get set up with all necessary computer accounts, tools & software
-   Get to know your peers
-   Become familiar with the Bren & NCEAS space, + more!

[Click here](https://ucsb.app.box.com/s/y1j1vvkgkvxfh8umjr3hpv0rw9kx0562) for a detailed orientation agenda.

#### Thursday, July 29^th^ - Bren Hall

| Time (PST)        | Activity                |
|-------------------|-------------------------|
| 9:00am - 9:30am   | Check-in & Breakfast    |
| 9:30am - 10:00am  | Welcome & Introductions |
| 10:00am - 11:00am | Bren 101 Presentation   |
| 11:00am - 12:15pm | Team Building Exercise  |
| 2:00pm - 4:00pm   | Mutual Respect Workshop |

#### Friday, July 30^th^ - NCEAS

| Time (PST)        | Activity                                                                |
|-------------------|-------------------------------------------------------------------------|
| 9:30am - 10:00am  | Welcome to NCEAS                                                        |
| 10:00am - 10:30am | NCEAS Tour                                                              |
| 10:30am - 12:00pm | Computer Orientation + [Software Installation](meds-install-guide.html) |
| 12:00pm - 1:00pm  | Lunch Mixer with NCEAS Scientists on the Terrace                        |

## Summer Intensive Courses

During the first 6 weeks of the MEDS program (August through mid-September), students will take 5 intensive courses:

-   **Week 1:** EDS 212: Essential Math in Environmental Data Science (2 units)
-   **Weeks 2 & 3:** EDS 221: Scientific Programming Essentials (4 units)
-   **Week 4:** EDS 214: Analytical Workflows & Scientific Reproducibility (2 units)
-   **Week 5:** EDS 215: Introduction to Data Storage & Management (2 units)
-   **Week 6:** EDS 216: Meta-analysis and Systematic Reviews (2 units)

For more detailed descriptions of the summer courses, see our [Courses](https://ucsb-meds.github.io/courses.html) page.

## Location

All Summer courses will be held at the new [NCEAS](https://www.nceas.ucsb.edu/) building (and new designated MEDS learning space!) in downtown Santa Barbara. The address is 1021 Anacapa Street.

NCEAS is \~11 miles (a 15 minute drive, without traffic) from the UC Santa Barbara campus, or a \~35 minute bus ride on the [24x line](https://sbmtd.gov/routes/route-24x/). The transit center downtown is \~3 blocks from NCEAS (a \<10 minute walk).

## A day in a Summer course

During intensive Summer courses, students should plan to arrive at NCEAS by 8:45am daily, ready for full days of learning (usually 9am - 5pm PST, M - F). Students generally should **not expect** additional assignments or MEDS-related work outside of those hours. In other words, courses will be structured so that all course requirements can be completed within the 9am - 5pm window while at NCEAS.

That doesn't mean you'll be watching lectures from 9am - 5pm! Summer session days will be active, varied, and flexible, and students can expect a combination of course content (e.g. lectures, computational labs, individual and group tasks) and built-in "flex time" for community-building, professional & career development activities, and more.

For example, a day during a Summer course might look like this:

|                   |                                                         |
|-------------------|---------------------------------------------------------|
| **Time (PST)**    | **Activity**                                            |
| 9:00am - 10:00am  | *Lecture 1 (60 min)*                                    |
| 10:00am - 11:00am | *Interactive Session 1 (60 min)*                        |
| 11:00am - 11:10am | *Break (10 min)*                                        |
| 11:10am - 12:00pm | *Flex time (50 min)*                                    |
| 12:00pm - 1:15pm  | *Lunch (75 min)*                                        |
| 1:15pm - 2:15pm   | *Lecture 2 (60 min)*                                    |
| 2:15pm - 3:15pm   | *Interactive Session 2 (45 min)*                        |
| 3:15pm - 5:00pm   | *Group & individual tasks (90 min)*                     |

With built-in breaks for coffee and lunch, interactive sessions for hands-on learning, and flex time for activities that change daily, we on the MEDS Team are working to make these days dynamic and fun while you build fundamental skills in environmental data science.

## Class activities

Summer is a special time for our MEDS students to bond both in and outside of class. You will be spending 6 weeks together from 9 am to 5 pm each day. While the coursework will be rigorous, we will also have dedicated breaks and events for relaxing, mingling and socializing. Thursday Happy Hour on the third floor terrace is a great opportunity to not only get to know your classmates, but also other MEDS and NCEAS staff, researchers, and faculty. We also look forward to celebrating important MEDS milestones, like both the halfway-point and completion of summer session.

# Fall

In Fall Quarter, MEDS students will complete 16 units of coursework. There are two 2-unit courses (EDS 213 and EDS 211) that only span 5 weeks, so in any week of the quarter students will be taking a total of 4 required courses.

-   **EDS 213:** Metadata Standards, Data Modeling and Data Semantics (2 units) - first 5 weeks
-   **EDS 211:** Team Science, Collaborative Analysis and Project Management (2 units) - second 5 weeks
-   **EDS 220:** Remote Sensing and Environmental Data (4 units)
-   **EDS 222:** Statistics for Environmental Data Science (4 units)
-   **EDS 223:** Spatial Analysis for Environmental Data Science (4 units)

## Schedule

In Fall, Winter and Spring quarters, MEDS courses will be held at both the Bren School (UCSB campus) and downtown at NCEAS. Students will *only have required courses / events at a single campus on any given day* - i.e., to minimize travel, we will not schedule required MEDS events at both campuses on the same day. **You can add the MEDS [google calendar here](https://calendar.google.com/calendar/u/0/embed?src=c_1886ai526iqschc9mnpj6cu753n60@resource.calendar.google.com&ctz=America/Los_Angeles)**.

For example, a week in Fall Quarter might look something like this:

+-----------+------------------------------------------------------------------+------------+
| **Day**   | Activities                                                       | **Campus** |
+===========+==================================================================+============+
| Monday    | -   8:00am - 9:15am: EDS 213 (weeks 1-5) or EDS 211 (weeks 6-10) | NCEAS      |
|           |                                                                  |            |
|           | -   9:30am - 10:45am: EDS 220                                    |            |
|           |                                                                  |            |
|           | -   11:00am - 12:00pm: Livestream Bren Seminar                   |            |
+-----------+------------------------------------------------------------------+------------+
| Tuesday   | -   9:30am - 10:45am: EDS 222                                    | Bren Hall  |
+-----------+------------------------------------------------------------------+------------+
| Wednesday | -   8:00am - 9:15am: EDS 213 (weeks 1-5) or EDS 211 (weeks 6-10) | NCEAS      |
|           |                                                                  |            |
|           | -   9:30am - 10:45am: EDS 220                                    |            |
|           |                                                                  |            |
|           | -   12:00pm - 12:45 pm: NCEAS Roundtable                         |            |
+-----------+------------------------------------------------------------------+------------+
| Thursday  | -   8:15am - 9:15am: Career workshop                             | Bren Hall  |
|           |                                                                  |            |
|           | -   9:30am - 10:45am: EDS 222                                    |            |
+-----------+------------------------------------------------------------------+------------+
| Friday    | -   9:00am - 12:00pm: EDS 223                                    | Bren Hall  |
+-----------+------------------------------------------------------------------+------------+

# Winter

In Winter Quarter, students will complete 16 units of coursework, three traditional academic courses and one 4 unit capstone project course.

-   **EDS 232:** Machine Learning in Environmental Science (4 units)
-   **EDS 240:** Data Visualization and Communication (4 units)
-   **EDS 241:** Environmental Policy Evaluation (4 units)
-   **EDS 411A:** Capstone Group Project A (4 units)

# Spring

In Spring Quarter, students will complete 12 units of coursework, three traditional academic courses and one 4 unit capstone project course.

-   **EDS 230:** Modeling Environmental Systems (4 units)
-   **EDS 231:** Text and Sentiment Analysis for Environmental Problems (2 units)
-   **EDS 242:** Ethics & Bias in Environmental Data Science (2 units)
-   **EDS 411B:** Capstone Group Project B (4 units)
