---
title: "What can I do before I start?"
output: 
  distill::distill_article:
    toc: true
---

Incoming students often ask "What can I do before I start the MEDS program to prepare?" 

There are **no required tasks** that admitted MEDS students are expected to complete before starting the program. However, for those of you who are excited to explore the landscape of Environmental Data Science a bit more before MEDS Orientation, here are some completely optional things you can do.  

## 1. Join communities

Yes, you should feel welcome to join even before you start MEDS, and even if you've never written a line of code before!

Joining and engaging with data science communities is a great way to build your Environmental Data Science network, stay up to date on new tools, methods, events, and initiatives, learn about professional opportunities, and to get support of all flavors (technical, emotional, etc.). 

Here are some places to start: 

### Eco-Data-Science {.unlisted .unnumbered}

[Eco-Data-Science](https://eco-data-science.github.io/), founded by MEDS Coordinator [Jamie Montgomery](https://www.jamiecmontgomery.com/) in 2015, is a volunteer-driven learning group that has become a model for coding clubs and communities around the world. During the academic year, Eco-Data-Science offers monthly workshops on wide-ranging topics in environmental data science topics from text analysis to high performance computing to basic data wrangling in R and Python. 

- [Join Eco-Data-Science](https://eco-data-science.github.io/) - click 'Talk to Us!' to join the Google group to receive updates, session alerts, and more
- Join the [Eco-Data-Science Slack workspace](ecodatascience.slack.com) - a great place to meet other members, see shared job postings, learn about upcoming events in Environmental Data Science, etc.

### Santa Barbara R-Ladies {.unlisted .unnumbered}

[Santa Barbara R-Ladies](https://www.meetup.com/rladies-santa-barbara/) is our local chapter of [R-Ladies](https://rladies.org/), "a world-wide organization to promote gender diversity in the R community." SB R-Ladies hosts ~5 - 6 events per year, including skill-building workshops, guest speakers, networking events, and more. All are welcome to join and participate, with the understanding that this group prioritizes supporting members from underrepresented genders in the R community. 

- [Join SB R-Ladies Meetup group](https://www.meetup.com/rladies-santa-barbara/)
- Follow [SB R-Ladies on Twitter](https://twitter.com/RLadiesSB)

### Santa Barbara R-Users Group {.unlisted .unnumbered}

The [Santa Barbara R-Users Group](https://www.meetup.com/Santa-Barbara-R-Users-Group/) is a local group that hosts sessions throughout the year to "bring Santa Barbara R users together to exchange information and ideas." Users and learners of all levels are welcome to join! Past sessions have included guest speakers and visitors, lightning talks, active coding lessons, and much more! 

- [Join the Santa Barbara R-Users Group](https://www.meetup.com/Santa-Barbara-R-Users-Group/)

### R for Data Science Online Learning Community {.unlisted .unnumbered}

The [R for Data Science Online Learning Community](https://www.rfordatasci.com/) is a supportive place where you can join groups, ask for help, learn about events and jobs, and network with other learners, teachers, and practitioners in the R community.

### Twitter {.unlisted .unnumbered}

We know, it seems like a weird suggestion - but Twitter is *the* place where the R community members get and share information. It is a treasure trove of resources, support, and direct access to data scientists across fields. Many data scientists use Twitter as a professional tool to share their work, ask questions, request feedback, and build collaborations. Give it a try! 

- Make a twitter account
- Follow a few groups & people Twitter: 

  - R for Data Science Learning Community: [\@R4DScommunity](https://twitter.com/R4DScommunity). 
  - WeAreRLadies (rotating curator, R-Ladies): [\@WeAreRLadies](https://twitter.com/WeAreRLadies). 
  - Mi-R (a space of belonging and support for people who identify as underrepresented minority R users): [\@miR_Commmunity](https://twitter.com/miR_community). 
  - PyLadies: [\@pyladies](https://twitter.com/pyladies)
  - Real Python: [\@realpython](https://twitter.com/realpython)
  - UCSB Eco-Data-Science: [\@ecodatasci](https://twitter.com/ecodatasci)
  - R-Ladies Santa Barbara: [\@RLadiesSB](https://twitter.com/RLadiesSB)
  - National Center for Ecological Analysis and Synthesis: [\@nceas](https://twitter.com/nceas)
        
- Not sure how to engage on Twitter? We know it can be weird & overwhelming at first! Check out the free book [Twitter for R Programmers](https://www.t4rstats.com/) by [Oscar Baruffa](https://twitter.com/OscarBaruffa) and [Veerle van Son](https://twitter.com/veerlevanson) for useful guidance.

## 2. Stretch your quantitative brain

If your brain is feeling a bit rusty on numbers & equations, you may want to stretch out your math muscles a bit before MEDS starts. Again: this is absolutely **not** required. We will do some warm-up stretches in EDS 212 (Essential Math in Environmental Data Science), the first course you'll take in MEDS. However, if you're really inspired to refresh some math skills before then, focus on algebra basics (e.g. the first four sessions in [Khan Academy's Algebra 1 module](https://www.khanacademy.org/math/algebra)).

We will do *all of this* in EDS 212, but if you're feeling especially nervous about math in the MEDS program, bringing algebra basics back to the forefront of your brain is a good place to start. 

## 3. Career development brainstorming & learning

During this 11-month master’s program, you will start formally working with our Bren Career Team
during Fall Quarter as you start refining your marketing documents, designing your online platforms, putting a job search process in place, and honing your professional and career skills.

While we understand you might not be 100% sure what jobs you would like to pursue, you will need to make your job search (career development) a priority if you want to land a job prior to graduation. The Career Team will work closely with you from Fall to Spring. But they have also created a summer assignment so you can hit the ground running once Fall arrives. 

Following orientation, the Career Team will assign you a “Career Path and Job Search Skills Summer Assignment” to complete by the end of your summer courses. This assignment will ask you to reflect and answer some questions and explore some resources. Since this is an 11-month graduate program, the goal is to get you thinking the right way from the start. You will have the entire summer to work on these tasks, but the Career Team has shared them now so you can get a head start.

### Create a career vision: Where you want to go, and where you should begin? {.unlisted .unnumbered}

Start to design a career path that will take you from where you are to where you want to go. Answering the following questions will help you get on the right path.

- Why did you decide to attend the Bren School?
- Looking into the future, what job(s) do you see yourself working when you have fulfilled your career goals and aspirations?
- What job do you plan to pursue following graduation that will start you on a path toward fulfilling your career aspirations? The job you would like to pursue after graduation is your “ideal job.”
- Identify 5 people who are working in a job that most closely aligns with your career aspirations (your future self).

    - Ask your contacts about their career path, how they started achieving their career goals, and how they came to realize their overall career aspirations.
    - Ask your contacts where they would recommend you start your career (job and companies).
    
- What is your ideal job after graduation? (Type of work, sector, geographic location)
- Make a list of the companies/organizations that interest you and where you would like to work to put your skills and passions to use. These are your “target organizations.”
- Make a list of the people you know or connections you have at each of your target organizations.

### Explore job search resources {.unlisted .unnumbered}

The Career Team has provided a list of books you can read to gain more knowledge on job search strategies, relationship building tactics, and interviewing skills.  

**Book recommendations:**

-	[The 2-Hour Job Search](https://2hourjobsearch.com/) by Steve Dalton
- [The 20-Minute Networking Meeting (Graduate Edition)](https://20mnm.com/#graduate) by Nathan A. Perez and Marcia Ballinger, PhD
<!-- - [Build a Career in Data Science](https://www.manning.com/books/build-a-career-in-data-science) by Emily Robinson and Jacqueline Nolis -->

**Additional books to explore if you have more time:**

-	[The 7 Habits of Highly Effective People](https://www.franklincovey.com/the-7-habits/) by Stephen Covey
- [No-Nonsense Job Interviews]() by Arnold G. Boldt
- [Captivate: The Science of Succeeding with People](https://www.scienceofpeople.com/captivate/) by Vanessa Van Edwards
- [Never Eat Alone](https://www.penguinrandomhouse.com/books/227558/never-eat-alone-expanded-and-updated-by-keith-ferrazzi-and-tahl-raz/) by Keith Ferrazzi


