---
title: "Workshop Materials"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

##############################
# load packages
##############################

library(googledrive)
library(googlesheets4)
library(kableExtra)
library(tidyverse)
library(here)

##############################
# load in google sheet - REQUEST ACCESS FROM SAM TO UPDATE THIS SHEET
##############################

workshops <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1SQ2IL8VP4McfCzvEeHjl0K6844j5l_5BfUTcS9_y4C4/edit?usp=sharing")

##############################
# filter for quarter
##############################

summer_workshops <- workshops %>% 
  filter(Quarter == "summer") %>% 
  select(-Quarter)

fall_workshops <- workshops %>% 
  filter(Quarter == "fall") %>% 
  select(-Quarter)

winter_workshops <- workshops %>% 
  filter(Quarter == "winter") %>% 
  select(-Quarter)

spring_workshops <- workshops %>% 
  filter(Quarter == "spring") %>% 
  select(-Quarter)
```

We are actively developing data science workshops, which are meant to supplement the MEDS curriculum and teach additional skills. Find links to our teaching materials below.

## Summer Workshops

```{r, echo = FALSE}
##############################
# add links
##############################

# CSS
summer_workshops[1,5] <- cell_spec("link",  "html", link = "https://ucsb-meds.github.io/customizing-websites-css/#1")
summer_workshops[1,6] <- cell_spec("link",  "html", link = "https://github.com/UCSB-MEDS/customizing-websites-css")

##############################
# build table 
##############################

summer_workshops %>% 
  kable(col.names = c("Date", "Workshop title", "Description", "Approximate duration", "Presentation materials", "GitHub repo"), format = "html", escape = FALSE) %>% 
  kable_styling(bootstrap_options = "striped") %>% 
  kableExtra::row_spec(1, extra_css = "border-bottom: 1px solid gainsboro") # %>% 
  #scroll_box(width = "100%", height = "400px") 
```


## Fall Workshops

```{r, echo = FALSE}
##############################
# add links
##############################\

# Blog
fall_workshops[1,5] <- cell_spec("link",  "html", link = "https://samanthacsik.github.io/posts/2021-09-21-my-first-test-post/")
fall_workshops[1,6] <- cell_spec("link",  "html", link = "https://github.com/UCSB-MEDS/writing-blogposts")

# Google
fall_workshops[2,5] <- cell_spec("link",  "html", link = "https://ucsb-meds.github.io/teach-me-how-to-google/#1")
fall_workshops[2,6] <- cell_spec("link",  "html", link = "https://github.com/UCSB-MEDS/teach-me-how-to-google")

# RStudio Tips & Tricks
fall_workshops[3,5] <- cell_spec("link", "html", link = "https://ucsb-meds.github.io/R-tips-and-tricks/#1")
fall_workshops[3,6] <- cell_spec("link", "html", link = "https://github.com/UCSB-MEDS/R-tips-and-tricks")

##############################
# build table 
##############################

fall_workshops %>% 
  kable(col.names = c("Date", "Workshop title", "Description", "Approximate duration", "Presentation materials", "GitHub repo"), format = "html", escape = FALSE) %>% 
  kable_styling(bootstrap_options = "striped") %>% 
  kableExtra::row_spec(1, extra_css = "border-bottom: 1px solid gainsboro") # %>% 
  #scroll_box(width = "100%", height = "400px") 
```


## Winter Workshops

```{r, echo = FALSE}
##############################
# add links
##############################

# Python (by Data Carpentries)
winter_workshops[1,5] <- cell_spec("link",  "html", link = "https://ucsbcarpentry.github.io/2022-01-04-ucsb-python/")
winter_workshops[1,6] <- cell_spec("link",  "html", link = "https://github.com/UCSBCarpentry/2022-01-04-ucsb-python")

# SQL (by Data Carpentries)
winter_workshops[2,5] <- cell_spec("link",  "html", link = "https://ucsbcarpentry.github.io/2022-02-04-ucsb-sql-online/")
winter_workshops[2,6] <- cell_spec("link",  "html", link = "https://github.com/UCSBCarpentry/2022-02-04-ucsb-sql-online")

# Intro to Shiny
winter_workshops[3,5] <- cell_spec("link",  "html", link = "https://ucsb-meds.github.io/shiny-workshop/#1")
winter_workshops[3,6] <- cell_spec("link",  "html", link = "https://github.com/UCSB-MEDS/shiny-workshop")

##############################
# build table 
##############################

winter_workshops %>% 
  kable(col.names = c("Date", "Workshop title", "Description", "Approximate duration", "Presentation materials", "GitHub repo"), format = "html", escape = FALSE) %>% 
  kable_styling(bootstrap_options = "striped") %>% 
  kableExtra::row_spec(1, extra_css = "border-bottom: 1px solid gainsboro") # %>% 
  #scroll_box(width = "100%", height = "400px") 
```

## Spring Workshops 

```{r, echo = FALSE}
##############################
# add links
##############################

# Intro to Cloud Computing
spring_workshops[1,5] <- cell_spec("link",  "html", link = "https://ucsb-meds.github.io/cloud-computing/#1")
spring_workshops[1,6] <- cell_spec("link",  "html", link = "https://github.com/UCSB-MEDS/cloud-computing")

##############################
# build table 
##############################

spring_workshops %>% 
  kable(col.names = c("Date", "Workshop title", "Description", "Approximate duration", "Presentation materials", "GitHub repo"), format = "html", escape = FALSE) %>% 
  kable_styling(bootstrap_options = "striped") %>% 
  kableExtra::row_spec(1, extra_css = "border-bottom: 1px solid gainsboro") # %>% 
  #scroll_box(width = "100%", height = "400px") 
```
